[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
exclude = [
    "src/bridge/**",
    "script/DeploySimpleAadhaarKYC.s.sol",
    "script/DeploySimpleKYCOnly.s.sol",
    "test/Contract.t.sol"
]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "https://rpc-mumbai.maticvigil.com/"
amoy = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }
